// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3Y6KYaG3Zzfx76CawBFbrMs7qWyEk0E',
    appId: '1:263160311042:web:5178ac3c1368cf324ae61b',
    messagingSenderId: '263160311042',
    projectId: 'app-weight',
    authDomain: 'app-weight.firebaseapp.com',
    storageBucket: 'app-weight.firebasestorage.app',
    measurementId: 'G-6GWPEB00RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyUTT0c4WcQfTduNYk9XiXP_LcT5H6p4c',
    appId: '1:263160311042:android:ac52278ebdae449c4ae61b',
    messagingSenderId: '263160311042',
    projectId: 'app-weight',
    storageBucket: 'app-weight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDFvPGC_-hEaBXKVzoMUm73-EN1fvMyo',
    appId: '1:263160311042:ios:b87806074c6fbf794ae61b',
    messagingSenderId: '263160311042',
    projectId: 'app-weight',
    storageBucket: 'app-weight.firebasestorage.app',
    iosBundleId: 'com.example.appWeight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWDFvPGC_-hEaBXKVzoMUm73-EN1fvMyo',
    appId: '1:263160311042:ios:b87806074c6fbf794ae61b',
    messagingSenderId: '263160311042',
    projectId: 'app-weight',
    storageBucket: 'app-weight.firebasestorage.app',
    iosBundleId: 'com.example.appWeight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd3Y6KYaG3Zzfx76CawBFbrMs7qWyEk0E',
    appId: '1:263160311042:web:56b761caf9fe7fe94ae61b',
    messagingSenderId: '263160311042',
    projectId: 'app-weight',
    authDomain: 'app-weight.firebaseapp.com',
    storageBucket: 'app-weight.firebasestorage.app',
    measurementId: 'G-YTPYNF5FHC',
  );
}
